### ISSUE TITLE
Link projects and issues upon creating a feature branch

### ISSUE THREAD

**Issue by BlackIsBlack** [SituDevelopment/automation#19]
**Is your feature request related to a problem? Please describe.**
When creating an issue in Github, you must first create a feature branch using the `feature-branch` command, and then manually link it and a project.

**Describe the solution you'd like**
**Require** an issue to be created for the given base branch before a feature branch will be created. Also the ability to assign a project would be very nice.

Perhaps the format could be:
```
feature-branch <test-repo> <test-feature branch> <issue-identifier> -p <project-name>
```

**Comment by willsawyerrrr** [comment]
The ability to "assign a project" is no longer required, as they are added by an action.

We still desire coupling development branches with development tasks in the form of issues.
